### PR TITLE
Log digest or image id as info level instead of debug

### PR DESCRIPTION
**Pull request by jkutner**
```
[builder]
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Reusing layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Reusing layer 'heroku/java:jre'
[exporter] *** Images:
[exporter]       index.docker.io/library/myimage:latest (ae41bec06d78)
[exporter]
[exporter] *** Image ID: ae41bec06d78175a2bfadbf0d39dd0e5ba9dcf046a5d8c2d76b8205eb419eac1
===> CACHING
[cacher] Reusing layer 'heroku/java:jdk'
[cacher] Caching layer 'heroku/java:maven_m2'
Successfully built image myimage
```

### CODE REVIEW

**Comment by ekcasey** [comment]
@nebhale @jkutner I would leave the last line and take the truncated value out of the previous lines. When the exporter saves to multiple tags it will just repeat the same digest needlessly.
Also it may require some annoying scrolling to grab it.

@nebhale I think we should only add the `sha256:` prefix in the registry digest case. I don't think the daemon likes prefixed IDs. Also, I think the digest ref already contains that prefix.

**Comment by jkutner** [comment]
@nebhale @ekcasey could we truncate the "Image ID: xxx" but print the full "Digest: sha:xxx"?

**Comment by nebhale** [comment]
Two options for I see consistency:

## `pack create-builder`
```
2019/10/03 22:14:31 localhost:5000/builder:latest: digest: sha256:d3f6b24ee0efe6a62c2ba429ed37e978f2dc7b8f66b2f9ff2286895a596c9cfb size: 2693
```

## `docker push`
```
latest: digest: sha256:029ba67679fec0341d9cd6d20ad86a58e6ab69b32b782d0fa6fdc069d7826bd7 size: 1364
```

I don't have a strong opinion either way.

**Comment by jkutner** [comment]
prefix + indent + tag + digest is a pretty long line. and if we're looking at `docker push` or `docker build` as prior art, what about this:

```
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Adding layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Adding layer 'heroku/jvm:jre'
[exporter] Digest: sha256:f204089ec44d866e4ba6ecfb86198efb5bc6bbb77278bdc194abd413e744a10a
===> CACHING
[cacher] Caching layer 'heroku/jvm:jdk'
Successfully built image docker.io/jkutner/myimage
```

This matches `docker push` with the digest line, but omits the image name during export. Instead, it puts the image name on the final line only, like `docker build`

The `docker build` output looks something like:

```
...
Removing intermediate container a67ec50c7048
 ---> d8acc14d9b6b
Successfully built d8acc14d9b6b
Successfully tagged docker.io/jkutner/myimage
```

**Comment by ekcasey** [comment]
@jkutner I agree we could truncate the image ID (not the digest) in the daemon case. The docker daemon can work with shortened SHAs.

The lifecycle can export to multiple tags (even though pack doesn't take advantage of that). Are you suggesting removing the tag statuses from export logs?

**Comment by jkutner** [comment]
Example output now w/ Image ID:

```
[builder]
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Reusing layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Reusing layer 'heroku/java:jre'
[exporter] *** Images (411e3d380a64):
[exporter]       index.docker.io/library/myimage:latest
===> CACHING
[cacher] Reusing layer 'heroku/java:jdk'
[cacher] Caching layer 'heroku/java:maven_m2'
Successfully built image myimage
```

And with Digest:

```
===> EXPORTING
[exporter] Adding layer 'app'
[exporter] Reusing layer 'config'
[exporter] Adding layer 'launcher'
[exporter] Reusing layer 'heroku/java:jre'
[exporter] *** Images (sha256:b8355e829ace5420ecd1c6cba6c61ed3f0345b2d6160ed5dad76c61b10e14f64):
[exporter]       index.docker.io/library/myimage:latest
===> CACHING
[cacher] Reusing layer 'heroku/java:jdk'
[cacher] Caching layer 'heroku/java:maven_m2'
Successfully built image myimage
```

**Comment by nebhale** [comment]
Love it. Ship it.

**Pull request merged**
