### PR TITLE
Use version from toml file as BuildpackMap key

### PR DESCRIPTION
**Pull request by jkutner**
This facilitates the implementation of https://github.com/buildpack/pack/issues/113

### CODE REVIEW

**Comment by sclevine** [comment]
I think this will break the `latest` symlinks.

**Comment by jkutner** [comment]
@sclevine what do you think about treating `latest` as a special value (either in lifecycle or the spec). That is, a buildpack would not be allowed to define it's version as `"latest"`. That would allow me to work around this.

**Comment by sclevine** [comment]
That restriction seems like a great idea to me. I don't think it makes the current proposed changes work with the `latest` symlink though.

**Comment by jkutner** [comment]
@sclevine correct, i would still have to adjust this PR, but I wanted to float that idea before doing so

**Comment by jkutner** [comment]
@sclevine @ekcasey added a test, but didn't use a symlink (i created a real dir with real files). I think that's probably a good idea?

**Pull request merged**
